sonar.projectKey=TEPIS
sonar.projectName=TEPIS
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3.8
sonar.host.url=http://localhost:9000
sonar.token= sqp_ed6c4a977b4208b0defe49c991c4cba7f7df93c9
